### PR TITLE
Fixed counts in statistics not resetting on book close

### LINKED ISSUE #47: Word counters do not reset after unloading a vocabulary book
Like the title says, when unloading a vocabulary book, the word counters on the StatisticsPanel (bottom right) are not reset to zero. I can provide a PR with a fix for this if you like.
Fixes #47

### PR DESCRIPTION
**Pull request by jdelange22**
Fixes #47

### CODE REVIEW

File: src/Vocup/Models/VocabularyBookStatistics.cs [hunk 1]
```diff
@@ -76,4 +76,14 @@ public void Refresh()
 
         OnPropertyChanged();
     }
+
+    public void Reset()
```
Comment (daniel-lerch) [inline src/Vocup/Models/VocabularyBookStatistics.cs:80]: I don't know why, but I never designed this class for unloading a vocabulary book. I would like to challenge you to change its design, e.g. making `VocabularyBookStatistics` nullable in `MainForm.cs` or making `book` nullable in this class so that there a proper mechanism for loading and unloading statistics. When no book is loaded you could also disable the statics panel like it is already done for most of the buttons.

**Review by daniel-lerch — CHANGES_REQUESTED** [review]

**Comment by jdelange22** [comment]
@daniel-lerch so I made book nullable in VocabularyBookStatistics.cs and upon change of this property I call `Refresh()` checking if `book` is null and if so resetting the counters to zero. This still involves manually setting the `book` property to null from the MainForm.cs. VocabularyBookStatistics cannot be made nullable in MainForm.cs as there is no direct reference from there.

File: src/Vocup/Models/VocabularyBookStatistics.cs (hunk 1 above)
Comment (daniel-lerch) [reply src/Vocup/Models/VocabularyBookStatistics.cs:80]: I took a more detailed look at the data model. I did not do a very great job when I designed it 6 years ago. `VocabularyBookStatistics` is the wrong place to fix this bug, though. In my opinion it would make most sense to reset the counters in `MainForm.UnloadBook` whenever a full unload is performed.

**Comment by jdelange22** [comment]
@daniel-lerch I changed the code to reset the counters in the Control itself from the MainForm's UnloadBook() function.
